from enum import Enum
from .models import *
from .base_model import Page
from .services.allowlists import Allowlists
from .services.blocklists import Blocklists
from .services.integrations import Integrations
from .services.decisions import Decisions
from .services.info import Info
from .services.metrics import Metrics
from .services.hub import Hub
from .http_client import ApiKeyAuth

class Server(Enum):
    production_server = 'https://admin.api.crowdsec.net/v1'

__all__ = [
    'Allowlists',
    'Blocklists',
    'Integrations',
    'Decisions',
    'Info',
    'Metrics',
    'Hub',
    'AllowlistCreateRequest',
    'AllowlistCreateResponse',
    'AllowlistGetItemsResponse',
    'AllowlistGetItemsResponsePage',
    'AllowlistGetResponse',
    'AllowlistGetResponsePage',
    'AllowlistItemUpdateRequest',
    'AllowlistItemUpdateResponse',
    'AllowlistItemsCreateRequest',
    'AllowlistScope',
    'AllowlistSubscriberEntity',
    'AllowlistSubscriberEntityPage',
    'AllowlistSubscribersCount',
    'AllowlistSubscriptionRequest',
    'AllowlistSubscriptionResponse',
    'AllowlistUpdateRequest',
    'AllowlistUpdateResponse',
    'ApiKeyCredentials',
    'AttacksMetrics',
    'BasicAuthCredentials',
    'BlocklistAddIPsRequest',
    'BlocklistCategory',
    'BlocklistContentStats',
    'BlocklistCreateRequest',
    'BlocklistDeleteIPsRequest',
    'BlocklistIncludeFilters',
    'BlocklistOrigin',
    'BlocklistSearchRequest',
    'BlocklistShareRequest',
    'BlocklistSources',
    'BlocklistStats',
    'BlocklistSubscriberEntity',
    'BlocklistSubscriberEntityPage',
    'BlocklistSubscribersCount',
    'BlocklistSubscription',
    'BlocklistSubscriptionRequest',
    'BlocklistSubscriptionResponse',
    'BlocklistUpdateRequest',
    'BlocklistUsageStats',
    'Body_uploadBlocklistContent',
    'CVESubscription',
    'ComputedMetrics',
    'ComputedSavedMetrics',
    'CtiAs',
    'CtiBehavior',
    'CtiCategory',
    'CtiCountry',
    'CtiIp',
    'CtiScenario',
    'DecisionCreateRequest',
    'DecisionCreateResponse',
    'DecisionResponse',
    'DecisionTargetModel',
    'DecisionTargetType',
    'DecisionsGetResponsePage',
    'DecisionsSortBy',
    'DecisionsSortOrder',
    'EntityType',
    'FingerprintSubscription',
    'GetRemediationMetricsResponse',
    'HTTPValidationError',
    'InfoResponse',
    'IntegrationCreateRequest',
    'IntegrationCreateResponse',
    'IntegrationGetResponse',
    'IntegrationGetResponsePage',
    'IntegrationType',
    'IntegrationUpdateRequest',
    'IntegrationUpdateResponse',
    'Links',
    'MetricUnits',
    'OriginMetrics',
    'OutputFormat',
    'Permission',
    'PricingTiers',
    'PublicBlocklistResponse',
    'PublicBlocklistResponsePage',
    'RawMetrics',
    'RemediationMetrics',
    'RemediationMetricsData',
    'Share',
    'SourceInfo',
    'SourceType',
    'Stats',
    'SubscriberEntityType',
    'ValidationError',
    'VendorSubscription',
    'AppsecConfigIndex',
    'AppsecRuleIndex',
    'CollectionIndex',
    'ContextIndex',
    'Index',
    'ParserIndex',
    'PostoverflowIndex',
    'ScenarioIndex',
    'VersionDetail',
    'ApiKeyAuth',
    'Server',
    'Page'
]