from enum import Enum
from .models import *
from .base_model import Page
from .services.allowlists import Allowlists
from .services.blocklists import Blocklists
from .services.integrations import Integrations
from .services.decisions import Decisions
from .services.engines import Engines
from .services.info import Info
from .services.metrics import Metrics
from .services.hub import Hub
from .services.cves import Cves
from .services.vendors import Vendors
from .services.products import Products
from .services.tracker_tags import TrackerTags
from .services.fingerprints import Fingerprints
from .services.tracker_events import TrackerEvents
from .http_client import ApiKeyAuth

class Server(Enum):
    production_server = 'https://admin.api.crowdsec.net/v1'

__all__ = [
    'Allowlists',
    'Blocklists',
    'Integrations',
    'Decisions',
    'Engines',
    'Info',
    'Metrics',
    'Hub',
    'Cves',
    'Vendors',
    'Products',
    'TrackerTags',
    'Fingerprints',
    'TrackerEvents',
    'AggregatedDecisionItem',
    'AggregatedDecisionsGetResponse',
    'AggregatedDecisionsGetResponsePage',
    'AggregatedDecisionsSortBy',
    'AllowlistCreateRequest',
    'AllowlistCreateResponse',
    'AllowlistGetItemsResponse',
    'AllowlistGetItemsResponsePage',
    'AllowlistGetResponse',
    'AllowlistGetResponsePage',
    'AllowlistItemUpdateRequest',
    'AllowlistItemUpdateResponse',
    'AllowlistItemsCreateRequest',
    'AllowlistScope',
    'AllowlistSubscriberEntity',
    'AllowlistSubscriberEntityPage',
    'AllowlistSubscribersCount',
    'AllowlistSubscription',
    'AllowlistSubscriptionRequest',
    'AllowlistSubscriptionResponse',
    'AllowlistUpdateRequest',
    'AllowlistUpdateResponse',
    'ApiKeyCredentials',
    'AttacksMetrics',
    'BasicAuthCredentials',
    'BlocklistAddIPsRequest',
    'BlocklistCategory',
    'BlocklistContentStats',
    'BlocklistCreateRequest',
    'BlocklistDeleteIPsRequest',
    'BlocklistIncludeFilters',
    'BlocklistOrigin',
    'BlocklistSearchRequest',
    'BlocklistShareRequest',
    'BlocklistSources',
    'BlocklistStats',
    'BlocklistSubscriberEntity',
    'BlocklistSubscriberEntityPage',
    'BlocklistSubscribersCount',
    'BlocklistSubscriptionRequest',
    'BlocklistSubscriptionResponse',
    'BlocklistUpdateRequest',
    'BlocklistUsageStats',
    'Body_uploadBlocklistContent',
    'CVESubscription',
    'ComputedMetrics',
    'ComputedSavedMetrics',
    'CtiAs',
    'CtiBehavior',
    'CtiCategory',
    'CtiCountry',
    'CtiIp',
    'CtiScenario',
    'DecisionCreateRequest',
    'DecisionCreateResponse',
    'DecisionMachineState',
    'DecisionMachineStateEnum',
    'DecisionResponse',
    'DecisionTargetModel',
    'DecisionTargetType',
    'DecisionsGetResponsePage',
    'DecisionsSortBy',
    'DecisionsSortOrder',
    'EngineGetResponse',
    'EngineGetResponsePage',
    'EntityType',
    'FingerprintSubscription',
    'GetRemediationMetricsResponse',
    'HTTPValidationError',
    'InfoResponse',
    'IntegrationCreateRequest',
    'IntegrationCreateResponse',
    'IntegrationGetResponse',
    'IntegrationGetResponsePage',
    'IntegrationType',
    'IntegrationUpdateRequest',
    'IntegrationUpdateResponse',
    'Links',
    'MetricUnits',
    'OperatingSystem',
    'OriginMetrics',
    'OutputFormat',
    'Permission',
    'PricingTiers',
    'PublicBlocklistResponse',
    'PublicBlocklistResponsePage',
    'RawMetrics',
    'RemediationMetrics',
    'RemediationMetricsData',
    'RemediationStats',
    'Share',
    'SourceInfo',
    'SourceType',
    'Stats',
    'SubscriberEntityType',
    'ValidationError',
    'VendorSubscription',
    'capi__entities__lists_subscriber_entity__BlocklistSubscription',
    'src__api__v1__models__integrations__BlocklistSubscription',
    'AppsecConfigIndex',
    'AppsecRuleIndex',
    'CollectionIndex',
    'ContextIndex',
    'Index',
    'ParserIndex',
    'PostoverflowIndex',
    'ScenarioIndex',
    'VersionDetail',
    'AdjustmentScore',
    'AffectedComponent',
    'AttackDetail',
    'AttackerObjective',
    'Behavior',
    'BlocklistSubscription',
    'CVEEventOutput',
    'CVEExploitationPhase',
    'CVEResponseDetailed',
    'CVEsubscription',
    'CWE',
    'Classification',
    'Classifications',
    'ExploitationPhase',
    'ExploitationPhaseChangeEventItem',
    'ExploitationPhaseChangeEventsResponsePage',
    'FacetBucket',
    'FingerprintEventOutput',
    'FingerprintRuleResponse',
    'FingerprintTimelineItem',
    'GetCVEIPsResponsePage',
    'GetCVEProtectRulesResponse',
    'GetCVEResponse',
    'GetCVESubscribedIntegrationsResponsePage',
    'GetCVEsResponsePage',
    'GetCVEsSortBy',
    'GetCVEsSortOrder',
    'GetFingerprintIPsResponsePage',
    'GetFingerprintRulesResponsePage',
    'GetFingerprintSubscribedIntegrationsResponsePage',
    'GetVendorIPsResponsePage',
    'GetVendorSubscribedIntegrationsResponsePage',
    'History',
    'IPItem',
    'IndicatorHttpPath',
    'IndicatorType',
    'IndicatorsSortBy',
    'IndustryRiskProfile',
    'IndustryType',
    'IntegrationResponse',
    'IntervalOptions',
    'IpsDetailsStats',
    'Location',
    'LookupImpactCVEItem',
    'LookupImpactFingerprintItem',
    'LookupImpactResponsePage',
    'LookupListItemWithStats',
    'LookupListWithStatsResponsePage',
    'MitreTechnique',
    'ProtectRule',
    'ProtectRuleTag',
    'Reference',
    'ScoreBreakdown',
    'Scores',
    'SinceOptions',
    'SubscribeCVEIntegrationRequest',
    'SubscribeFingerprintIntegrationRequest',
    'SubscribeVendorIntegrationRequest',
    'ThreatContext',
    'TimelineItem',
    'TopProductItem',
    'VendorSortBy',
    'VendorStatsResponse',
    'ApiKeyAuth',
    'Server',
    'Page'
]