name: "Crowdsec Service API SDK release"

on:
  release:
    types:
      - released
      - prereleased

jobs:
  publish-on-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/crowdsec-service-api-sdk
    permissions:
      id-token: write
    needs: [ create-release ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1